# Generated by Django 2.0 on 2019-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=5, unique=True)),
                ('sname', models.CharField(max_length=50)),
                ('singer', models.CharField(max_length=50)),
                ('cost', models.IntegerField()),
                ('desc', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
