# Generated by Django 2.0 on 2019-04-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20190406_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
