# Generated by Django 2.0 on 2019-04-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20190406_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='image',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
