# Generated by Django 2.0 on 2019-04-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0005_auto_20190406_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='try',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
