# Generated by Django 2.0 on 2019-04-07 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20190406_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='try',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
