# Generated by Django 2.0 on 2019-04-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0010_song_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='musics/'),
        ),
    ]
