# Generated by Django 2.0 on 2019-04-17 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0013_auto_20190417_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, default='', upload_to='musics'),
            preserve_default=False,
        ),
    ]
