# Generated by Django 2.0 on 2019-04-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0014_auto_20190417_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='file',
            field=models.FileField(blank=True, upload_to='musics/songs'),
        ),
    ]
